# note: this docker-compose file is intended to define the *building* of
# job-runner images, and running them locally in dev, not for running them in
# production
services:
  prod:
    # image name, both locally and public
    image: job-runner
    build:
      context: ..
      # path relative to context
      dockerfile: docker/Dockerfile
      # the prod stage in the Dockerfile
      target: job-runner-prod
      # should speed up the build in CI, where we have a cold cache
      cache_from:  # should speed up the build in CI, where we have a cold cache
        - ghcr.io/opensafely-core/base-docker
        - ghcr.io/opensafely-core/job-runner
      args:
        # this makes the image work for later cache_from: usage
        - BUILDKIT_INLINE_CACHE=1
        # env vars should be supplied by just/make
        - BUILD_DATE
        - GITREF
    # use dockers builitin PID daemon
    init: true
    # paths relative to docker-compose.yaml
    volumes:
      # use the default dev workdir
      - ../workdir:/workdir
      # used to configure ssh access for docker
      - ./ssh:/home/appuser/.ssh
    # ensure WORKDIR environment points to fixed location
    environment:
      # default dev config
      WORKDIR: /workdir
      MEDIUM_PRIVACY_STORAGE_BASE: /workdir/workspaces
      HIGH_PRIVACY_STORAGE_BASE: /workdir/workspaces
      # use docker over SSH to avoid socket file permissions
      DOCKER_HOST: ssh://${DOCKER_USER}@${DOCKER_ADDR}

  # main development service
  dev:
    extends:
        service: prod
    image: job-runner-dev
    container_name: job-runner-dev
    # running as a specific uid/gid allows files written to mounted volumes by
    # the docker container's default user to match the host user's uid/gid, for
    # convienience.
    user: ${DOCKER_USERID:-1000}:${DOCKER_GROUPID:-1000}
    build:
      # the dev stage in the Dockerfile
      target: job-runner-dev
      # pass the uid/gid as build arg
      args:
        - USERID=${DOCKER_USERID:-1000}
        - GROUPID=${DOCKER_GROUPID:-1000}
    # paths relative to docker-compose.yaml file
    env_file:
      - ../.env
    volumes:
      - ..:/app
      - ../workdir:/work_dir

  # test runner service - uses dev-image with a different command
  test:
    extends:
        service: dev
    container_name: job-runner-test
    # override command
    command: /opt/venv/bin/pytest
